feat: logging improvement
topology-foundation/ts-topology pull request #102
Opened 2024-08-07 20:52 UTC by JanLewDev

#67

2024-08-12 09:58 UTC, d-roak requested changes

2024-08-12 09:58 UTC, d-roak commented on packages/network/src/node.ts
> +let sendGroupMessageRandomPeerLogger: Logger<ILogObj> = new Logger();
have only, one logger per package. Prepend all the messages from ea pkg with it's name: `topology::{pkg_name}`

2024-08-12 09:58 UTC, d-roak commented on packages/network/src/node.ts
> +    mainLogger.settings.name = "topology:network";
yep, like this !! do "::" instead

2024-08-12 09:58 UTC, d-roak commented on packages/node/src/index.ts
> +  network_config: TopologyNetworkNodeConfig;
why?

2024-08-12 09:58 UTC, d-roak commented on packages/network/src/node.ts
> +  tslogconfig: ISettingsParam<ILogObj>;
```suggestion
  tslog_config: ISettingsParam<ILogObj>;
```

2024-08-12 09:58 UTC, d-roak commented on packages/network/src/node.ts
> +  tslogconfig: ISettingsParam<ILogObj>;
this is setted up with json files, what are the options for it? did you tested with the config files?

2024-08-12 09:58 UTC, d-roak commented on tsconfig.json
> +    "inlineSourceMap": true
why?

2024-08-12 09:58 UTC, d-roak commented on packages/node/tslog.config.ts
> +export default tslogconfig;
should be in the existing config files

2024-08-12 09:58 UTC, d-roak commented on packages/node/tsconfig.json
> +  "include": ["src/**/*.ts", "./*.config.ts"]
we are dropping the `tslog.config.ts`, you can revert this

2024-08-12 09:58 UTC, d-roak commented on packages/node/src/index.ts
>  export interface TopologyNodeConfig {
node also has a tslog_config that can be different from the network config

by default, the network will be equal to the node, but they can be set to be different

2024-08-12 10:33 UTC, JanLewDev commented on tsconfig.json
> +    "inlineSourceMap": true
![image](https://github.com/user-attachments/assets/15d3c783-9d1e-4b60-b55a-1ed71a6e5500)
so the line is referenced correctly

2024-08-12 12:45 UTC, JanLewDev commented on packages/network/src/node.ts
> +  tslogconfig: ISettingsParam<ILogObj>;
should it be a new json file or add to tsconfig.json?

2024-08-12 12:47 UTC, JanLewDev commented on packages/node/tslog.config.ts
> +export default tslogconfig;
tsconfig.json, right?

2024-08-12 12:55 UTC, JanLewDev commented on packages/node/tslog.config.ts
> +export default tslogconfig;
so the tsconfig.json for node would look something like this?
```typescript
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "dist"
  },
  "references": [
    {
      "path": "../crdt"
    },
    {
      "path": "../network"
    },
    {
      "path": "../object"
    }
  ],
  "include": ["src/**/*.ts"],
  "tslog_config": {
    "minLevel": 3, // 3 = INFO
    "type": "pretty", // "pretty" | "json" | "hidden" 
    "hideLogPositionForProduction": true
  }
}
```

2024-08-19 15:07 UTC, d-roak requested changes

2024-08-19 15:07 UTC, d-roak commented on packages/network/src/node.ts
> +let mainLogger: Logger<ILogObj> = new Logger();
rename it to `log`, so we can use `log.info()`

2024-08-19 15:07 UTC, d-roak commented on packages/network/src/node.ts
```suggestion
```

2024-08-19 15:07 UTC, d-roak commented on packages/node/configs/example.json
> +      }
only options that exist?

2024-08-19 15:07 UTC, d-roak commented on packages/node/tslog.config.ts
> +export default tslogconfig;
are you still using this?

2024-08-19 15:07 UTC, d-roak commented on packages/node/src/index.ts
> +      if(!this._config) this._config = {};
this shouldn't be inside the prev if

2024-08-20 07:01 UTC, d-roak approved these changes
lgtm

2024-08-20 07:01 UTC, merged