Improving Node Discovery via DHT Announcements - fixes  #152
topology-foundation/ts-topology pull request #184
Opened 2024-10-02 07:40 UTC by elielnfinic

### PR Overview:

This pull request addresses issue #152, focusing on enhancing node discovery for peers subscribed to specific topics by utilizing the DHT (Distributed Hash Table) rather than relying on a centralized PubSub mechanism.

### Summary of Changes:
DHT Integration:  Enabled DHT on the node, allowing topics to map directly to the peers subscribed to them.
Updated `packages/network/node.ts` file:

Added methods: `putDataOnDHT()getDataFromDHT(), announcePeerOnDHT(), removePeerFromDHT(), getPeersOnTopicFromDHT()`

Created a new private property:  `_dht`

Added the following external libraries to the network package:
	•	@libp2p/kad-dht
	•	@libp2p/peer-id
	•	@it-last

2024-10-02 17:28 UTC, d-roak requested changes
partial review

2024-10-02 17:28 UTC, d-roak commented on packages/network/package.json
don't change indentation

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +	PeerInfo,
not used

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +	EventHandler,
not used

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +	removePublicAddressesMapper,
not used

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +import { toString as uint8ToString } from "uint8arrays";
keep consistency `uint8ArrayToString`

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +				dht: kadDHT({}),
keep consistency, when not passing configs, don't pass anything as an input

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +		const peersOnTopic = await this._dht?.get(uint8Topic);
no need for `await`

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +	async getDataFromDHT(key: Uint8Array): Promise<Uint8Array | undefined> {
why do we need this method since we have `getPeersOnTopicFromDHT` ?

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +				await this._node.dial(peerId);
can't do this. put a `topic_discovery_peers_threshold` variable in the network config and use that threshold as the minimum number of peers.
If it falls down the threshold we try to connect, if it's equal we skip (this is the same everywhere, might segment this logic)

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +			return undefined;
return false here

2024-10-02 17:28 UTC, d-roak commented on packages/network/src/node.ts
> +			console.log("Successfully stored data in DHT");
change this log to the same format as the other logs

2024-10-03 02:49 UTC, elielnfinic commented on packages/network/src/node.ts
> +		const peersOnTopic = await this._dht?.get(uint8Topic);
You are right, I have just tested it.

2024-10-03 02:50 UTC, elielnfinic commented on packages/network/src/node.ts
> +				await this._node.dial(peerId);
Added a test to make sure I can't dial myself.

2024-10-03 03:17 UTC, elielnfinic commented on packages/network/src/node.ts
> +	async getDataFromDHT(key: Uint8Array): Promise<Uint8Array | undefined> {
I have removed it. Thank you for pointing that out.

2024-10-04 04:13 UTC, d-roak commented on packages/network/package.json
not resolved

2024-10-04 04:51 UTC, elielnfinic commented on packages/network/package.json
I have resolved it.

2024-10-28 22:04 UTC, closed without merging