Improving Node Discovery via DHT Announcements - fixes #152
topology-foundation/ts-topology pull request #212
Opened 2024-10-28 22:03 UTC by elielnfinic

This PR enhances peer discovery by implementing DHT, addressing issue #152.

The DHT-based discovery mechanism provides greater scalability compared to PubSub and offers additional advantages, including more efficient and persistent peer connections.

In addition to updating the discovery mechanism, the grid example UI has also been updated to reflect this new peer discovery approach.

2024-11-04 14:06 UTC, d-roak requested changes
refactor all the examples

2024-11-04 14:06 UTC, d-roak commented on examples/grid/vite.config.mts
> +import { fs } from "memfs";
why?

2024-11-04 14:06 UTC, d-roak commented on packages/network/src/node.ts
> +				const stream = await this._node.dial(multiaddr(addr));
when are you using the stream?

2024-11-04 14:06 UTC, d-roak commented on packages/network/src/node.ts
> +					// "/dns4/topology-1.nfinic.com/tcp/4430/wss/p2p/12D3KooWC6sm9iwmYbeQJCJipKTRghmABNz1wnpJANvSMabvecwJ",
this can't be merged as is. This assumes that people are running local bootstrap nodes

2024-11-04 14:06 UTC, d-roak commented on packages/network/src/node.ts
> +	}
not being used

2024-11-04 14:06 UTC, d-roak commented on packages/network/src/node.ts
> +			console.log("::start::peer::connect", e.detail);
this and all `console.log` should be changed to `log`

2024-11-04 15:35 UTC, elielnfinic commented on examples/grid/vite.config.mts
> +import { fs } from "memfs";
Used it at a certain time but forgot to remove it. Will remove it.

2024-11-04 15:37 UTC, elielnfinic commented on packages/network/src/node.ts
> +				const stream = await this._node.dial(multiaddr(addr));
I used it for some tests, will remove it.

2024-11-04 15:38 UTC, elielnfinic commented on packages/network/src/node.ts
> +	}
I am using it in the example.

2024-11-04 15:39 UTC, elielnfinic commented on packages/network/src/node.ts
> +			console.log("::start::peer::connect", e.detail);
Sure.

2024-11-04 16:59 UTC, d-roak requested changes

2024-11-04 16:59 UTC, d-roak commented on packages/network/src/node.ts
> +	}
ahh, we won't add this function. If the app developers want to check this logic, they should put it in their application. Also the comment is not making sense. The node should have the local multiaddrs as soon as it starts, the relay just adds a few more addresses

2024-11-04 16:59 UTC, d-roak commented on packages/network/src/node.ts
> +		this._node.addEventListener("peer:connect", async (e) => {});
why do we have an empty event listener?

2024-11-04 16:59 UTC, d-roak commented on examples/grid/src/index.ts
> +	}, 1000);
having some type of handler is preferable. You are rendering every second even if there are no updates

2024-11-04 16:59 UTC, d-roak commented on packages/network/src/node.ts
> +					"/dns4/topology-1.nfinic.com/tcp/4430/wss/p2p/12D3KooWC6sm9iwmYbeQJCJipKTRghmABNz1wnpJANvSMabvecwJ",
Even though you are the founder of https://nfinic.com/, we won't have other companies dependencies in the codebase
Let's setup the bootstrap nodes for topology first and then merge this with those in the hardcoded

2024-11-04 17:02 UTC, elielnfinic commented on packages/network/src/node.ts
> +					"/dns4/topology-1.nfinic.com/tcp/4430/wss/p2p/12D3KooWC6sm9iwmYbeQJCJipKTRghmABNz1wnpJANvSMabvecwJ",
Good catch! Sorry, I had to delete that line, I deleted droak.sh line.

2024-11-13 06:54 UTC, d-roak commented
close in favor of #251

2024-11-13 06:54 UTC, closed without merging