feat: fix root hash, add DAG testcases, DFS function
topology-foundation/ts-topology pull request #220
Opened 2024-10-29 10:25 UTC by hoangquocvietuet

2024-10-29 16:04 UTC, d-roak commented on packages/object/src/hashgraph/index.ts
> +	DFS(visited: Map<Hash, number> = new Map()): Hash[] {
why using number instead of `bool`?

2024-10-29 16:05 UTC, d-roak commented on packages/object/src/hashgraph/index.ts
> +import { assert } from "node:console";
not used?

2024-10-29 16:06 UTC, d-roak commented on packages/object/tests/hashgraph.test.ts
> +		expect(obj2.hashGraph.selfCheckConstraints()).toBe(true);
test putting two roots and check if it's false

2024-10-29 16:44 UTC, JanLewDev commented on packages/object/src/hashgraph/index.ts
> +	DFS(visited: Map<Hash, number> = new Map()): Hash[] {
Visited is set to 1 before calling children and 2 after the loop, not sure of the significance of setting it to 2

2024-10-30 09:50 UTC, hoangquocvietuet commented on packages/object/tests/hashgraph.test.ts
> +import { before } from "node:test";
delete it

2024-10-30 10:01 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +	DFS(visited: Map<Hash, number> = new Map()): Hash[] {
If we avoid using numbers and instead set 'visited' to 2, we risk incorrectly detecting a cycle where there isn't one due to the properties of DFS. For example, consider the graph with edges A -> B, A -> C, and B -> C. If we first visit A, then C, and later A -> B -> C, we can't determine if C was visitvisited ined in the current DFS recursion or a previous one. This is why we use the number 2 to update and keep track of the visitation state more accurately.

2024-10-30 10:02 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +					console.error("Cycle detected.");
changed

2024-10-30 11:42 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +				if (visited.get(child) === 1) {
I think these numbers should not be hardcoded. You can try using an enum to prevent misunderstandings.

2024-10-30 15:34 UTC, winprn commented on packages/object/tests/hashgraph.test.ts
> +		// expect(obj2.hashGraph.selfCheckConstraints()).toBe(true);
consider delete the line?

2024-10-31 04:26 UTC, hoangquocvietuet commented on packages/object/tests/hashgraph.test.ts
> +		// expect(obj2.hashGraph.selfCheckConstraints()).toBe(true);
readd it

2024-10-31 04:26 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +				if (visited.get(child) === 1) {
add it

2024-10-31 06:42 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +export enum DepthFirstSearchState {
enum values should be uppercas

2024-10-31 06:44 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +export enum DepthFirstSearchState {
done

2024-10-31 07:03 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +	// Time complexity: O(V + E), Space complexity: O(V)
you should remove the useless comments, as Oak suggested

2024-10-31 07:05 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +		// Temporary fix: don't add the vertex if the dependencies are not present in the local HG.dw
i guess this is a typo mistake

2024-10-31 07:06 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +		// Temporary fix: don't add the vertex if the dependencies are not present in the local HG.dw
removed

2024-10-31 07:11 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +	// Time complexity: O(V + E), Space complexity: O(V)
i think i would be fine for later contributor

2024-10-31 12:28 UTC, d-roak commented on packages/object/src/hashgraph/index.ts
> +	// Time complexity: O(V + E), Space complexity: O(V)
yes, remove it pls

2024-10-31 13:17 UTC, trungnotchung commented
lgtm

2024-10-31 13:19 UTC, trungnotchung approved these changes
lgtm

2024-11-01 02:28 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +	// Time complexity: O(V + E), Space complexity: O(V)
removed

2024-11-01 03:19 UTC, winprn requested changes

2024-11-01 03:53 UTC, d-roak commented on packages/object/src/hashgraph/index.ts
>  					log.error("::hashgraph::DFS: Cycle detected");
?? isn't "::DFS"?

2024-11-01 04:10 UTC, winprn approved these changes
Let's ship it! 🚀

2024-11-01 07:31 UTC, JanLewDev approved these changes
lgtm

2024-11-01 07:38 UTC, merged