feat: add dropped array, find next function in bitset
topology-foundation/ts-topology pull request #226
Opened 2024-11-01 02:15 UTC by hoangquocvietuet

2024-11-01 03:37 UTC, winprn requested changes

2024-11-01 03:37 UTC, winprn commented on packages/object/tests/hashgraph.test.ts
why the comments got formatted?

2024-11-01 03:37 UTC, winprn commented on packages/object/src/linearize/pairSemantics.ts
> +						j = i;
why would it be `j = i` instead of the original `j = order.length`

2024-11-01 03:37 UTC, winprn commented on packages/object/src/hashgraph/index.ts
> +		if (currentIndex === undefined) return undefined;
I think you can just check the logic in one statement, no need for extra variable

2024-11-01 07:42 UTC, hoangquocvietuet commented on packages/object/tests/hashgraph.test.ts
idk the biome toolchain did

2024-11-01 07:57 UTC, JanLewDev requested changes
This approach can also speed up `linearizeMultiple`

2024-11-01 07:57 UTC, JanLewDev commented on packages/object/src/hashgraph/index.ts
> +	findNextUnusuallyRelated(hash: Hash, start: number): number | undefined {
```suggestion
	findNextCausallyUnrelated(hash: Hash, start: number): number | undefined {
```

2024-11-05 04:10 UTC, hoangquocvietuet commented on packages/object/src/linearize/pairSemantics.ts
> +						j = i;
To break the inner loop, we set j = order.length. However, since this is a swap operation between i and j, nothing is dropped and we can continue with the same i. For the loop to proceed, we need to find the next causally unrelated index for j, thus we set j = findNextCausallyUnrelated(i) to continue the loop.

2024-11-05 04:11 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +		if (currentIndex === undefined) return undefined;
changed

2024-11-05 04:12 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/index.ts
> +	findNextUnusuallyRelated(hash: Hash, start: number): number | undefined {
changed

2024-11-05 04:12 UTC, hoangquocvietuet commented on packages/object/src/linearize/pairSemantics.ts
> +			if (dropped[i]) break;
Yes, exactly. Imagine the case when ActionType.DropLeft occurs.

2024-11-05 04:38 UTC, winprn commented on packages/object/tests/hashgraph.test.ts
please help reverting it 🙏

2024-11-10 12:12 UTC, trungnotchung commented on packages/object/src/linearize/pairSemantics.ts
> +						j = i;
i think we shouldn’t continue with j = i. In the previous approach, we broke the inner loop but continued with the same i to ensure we iterate over all vertices in topological sort order.

2024-11-10 12:12 UTC, trungnotchung commented on packages/object/src/linearize/pairSemantics.ts
> +						reachableState.swap(i, j);
it doesn’t solve the problem when we want to swap the positions of order[i] and order[j] also requires updating the reachablePredecessors of other nodes. maybe this approach does not work with current pairSemantics.

2024-11-10 16:38 UTC, JanLewDev commented on packages/object/src/hashgraph/index.ts
> +		return new ReachableState(result, this.vertices);
I agree with this. Imo it overcomplicates things and doesn't actually make `ActionType.Swap` work

2024-11-12 06:16 UTC, hoangquocvietuet commented on packages/object/src/linearize/pairSemantics.ts
> +						j = i;
Setting j = i allows us to continue with the same i as in the previous approach and effectively resets j. It’s the same process.

2024-11-12 06:17 UTC, hoangquocvietuet commented on packages/object/src/linearize/pairSemantics.ts
> +			if (dropped[i]) break;
The break keyword only exits the switch case, not the outer loop. Please make a note of this.

2024-11-12 07:39 UTC, hoangquocvietuet commented on packages/object/src/hashgraph/bitset.ts
> +		}
How can we find the first zero bit in O(1) time? Using bitwise operations still results in O(n/32) complexity due to looping through byteIndex.

2024-11-19 20:42 UTC, JanLewDev commented on packages/object/src/hashgraph/index.ts
> +	findNextUnusuallyRelated(hash: Hash, start: number): number | undefined {
```suggestion
	findNextCausallyUnrelated(hash: Hash, start: number): number | undefined {
```
it was already changed, but reverted?

2024-11-20 02:56 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +	findNextUnusuallyRelated(hash: Hash, start: number): number | undefined {
i changed the function name

2024-11-22 08:09 UTC, hoangquocvietuet commented
The logic part looks good to me.

2024-11-22 08:54 UTC, JanLewDev approved these changes
lgtm

2024-11-23 07:52 UTC, d-roak approved these changes

2024-11-23 07:52 UTC, merged