Fixing vertex dependencies issue
topology-foundation/ts-topology pull request #247
Opened 2024-11-12 13:09 UTC by elielnfinic

This PR fixes issue #185 
When a peer joins a CRO, it synchronizes the two peers vertex before merging them.

2024-11-12 13:21 UTC, elielnfinic reviewed
I know some code are weird on try and catches, please let me know what you think.

2024-11-12 16:54 UTC, d-roak requested changes
Overall the code quality is pretty poor. Let's try to make it cleaner

2024-11-12 16:54 UTC, d-roak commented on packages/node/src/handlers.ts
> +		}
Was there a bug here? For sure you are not supposed to restart the sync process in the middle of it

2024-11-12 16:54 UTC, d-roak commented on packages/node/src/handlers.ts
> +		}
this code is crazy
if() -> catch() -> try()

not clean at all

2024-11-12 16:54 UTC, d-roak commented on packages/node/src/handlers.ts
> +		if (updateMessage.vertices.length === 0) return false;
why is this check here? it's independent of the merge operation

2024-11-12 16:54 UTC, d-roak commented on packages/node/src/handlers.ts
> +		_merge();
syncObject is async, it will be sent over the network. Doesn't make sense to have the merge being called after

2024-11-12 16:54 UTC, d-roak commented on packages/object/src/hashgraph/index.ts
> +			throw new Error("Invalid dependency detected.");
Like the `throw` here, did you double checked everytime this function is called is not depending on the previous `return ""`?

2024-11-12 17:25 UTC, elielnfinic commented on packages/node/src/handlers.ts
> +		if (updateMessage.vertices.length === 0) return false;
If `updateMessage.vertices.length === 0`, I can't find the peerId.

2024-11-12 18:03 UTC, elielnfinic commented on packages/node/src/handlers.ts
> +		}
I have updated the logic, I check the name of error.

2024-11-13 12:07 UTC, elielnfinic commented on packages/node/src/handlers.ts
> +		}
I have changed to `callback` approach.

2024-11-13 12:07 UTC, elielnfinic commented on packages/object/src/hashgraph/index.ts
> +			throw new Error("Invalid dependency detected.");
Have removed this.

2024-11-13 12:08 UTC, elielnfinic commented on packages/node/src/handlers.ts
> +		_merge();
Now using async.

2024-11-14 11:15 UTC, d-roak requested changes

2024-11-14 11:15 UTC, d-roak commented on packages/node/src/handlers.ts
>  	const updateMessage = NetworkPb.Update.decode(data);
doesn't this has the sender node id already?

2024-11-14 11:15 UTC, d-roak commented on packages/node/src/handlers.ts
> +	await node.syncObject(updateMessage.objectId, senderPeerId);
why are you syncing ALWAYS when you receive an update?

2024-11-14 11:15 UTC, d-roak commented on packages/node/src/handlers.ts
> +		await node.syncObject(object.id, sender);
why are u starting a sync process in the middle of a sync?

2024-11-15 02:46 UTC, d-roak approved these changes

2024-11-15 05:20 UTC, trungnotchung approved these changes
lgtm

2024-11-16 10:11 UTC, merged