feat: add CROState to vertices (WIP)
topology-foundation/ts-topology pull request #263
Opened 2024-11-18 19:11 UTC by JanLewDev

2024-11-21 05:00 UTC, d-roak commented on packages/object/src/index.ts
> +	// root has in-degree 0
out-degree?

2024-11-21 17:25 UTC, JanLewDev commented on packages/object/src/index.ts
> +	// root has in-degree 0
It's the in-degree when looking at forward edges, which we are traversing from the root in `topoSortPast`

2024-11-22 05:18 UTC, trungnotchung commented on packages/object/src/index.ts
> +	pastInDegree: Map<Hash, number>;
why don't we store the topological sorted vertices instead of pastInDegree?

2024-11-25 01:22 UTC, d-roak requested changes

2024-11-25 01:22 UTC, d-roak commented on packages/object/src/index.ts
> +		past: Set<Hash> = new Set(),
```suggestion
		linearizedOperations: Operation[],
		past: Set<Hash>,
```

there's no case that the constructor should be passed without this inputs

2024-11-25 01:22 UTC, d-roak commented on packages/object/src/index.ts
> +	// root has in-degree 0
requires interpretation. Why is it useful to have it in the comments?

2024-11-25 01:22 UTC, d-roak commented on packages/object/src/index.ts
> +		}
the first get is redundant. You are going to iterate it anyway on the loop

2024-11-25 01:22 UTC, d-roak commented on packages/object/src/index.ts
> +				...(this.states.get(dep)?.past || new Set<string>()),
`this.states.get(dep)?.past` is only undefined if `get()` fails to return. It should be checked beforehand, it shouldn't execute without prompting an error

2024-11-25 01:22 UTC, d-roak commented on packages/object/src/linearize/pairSemantics.ts
> +	subgraph?: Set<Hash>,
not consistent

2024-11-25 07:35 UTC, trungnotchung commented on packages/object/src/hashgraph/index.ts
> +		this.depthFirstSearch(undefined, visited);
could you change "past" to an optional parameter so that it's not required to be passed here?

2024-11-25 07:35 UTC, trungnotchung commented on packages/object/src/index.ts
> +			this.states.get(vertex.dependencies[0])?.past || new Set();
```suggestion
		let past: Set<Hash> = new Set();
```
it can help make the logic less complex

2024-11-25 07:35 UTC, trungnotchung commented on packages/object/src/index.ts
> +			new CROState(this.cro as CRO, this.hashGraph.linearizeOperations(), past),
this cro will be a reference

2024-11-25 07:35 UTC, trungnotchung commented on packages/object/src/index.ts
> +				);
this code is duplicate, you should write a function to do it

2024-11-26 22:32 UTC, JanLewDev commented on packages/object/src/linearize/multipleSemantics.ts
> +	return partialLinearization(hashGraph, origin, subgraph);
What the purpose of separating? full and partial only differ at the top few lines

2024-11-27 12:07 UTC, trungnotchung commented on packages/object/src/linearize/multipleSemantics.ts
> +	return partialLinearization(hashGraph, origin, subgraph);
updated

2024-11-28 13:46 UTC, JanLewDev commented on packages/object/tests/hashgraph.test.ts
> +import exp from "constants";
is this used?

2024-11-29 09:00 UTC, trungnotchung commented on packages/object/tests/hashgraph.test.ts
> +import exp from "constants";
no, i removed them

2024-12-03 07:29 UTC, d-roak commented on packages/object/src/index.ts
>  }
why doing this instead of creating a type for CROState?

2024-12-03 07:29 UTC, d-roak commented on packages/object/src/index.ts
> +	originalCRO: CRO;
why do we need the original cro? can't we copy from the `cro` instance?

2024-12-03 07:29 UTC, d-roak commented on packages/object/tests/hashgraph.test.ts
revert the comments on this file

2024-12-03 07:29 UTC, d-roak commented on packages/object/tests/hashgraph.test.ts
> +		*/
format the comments to be readable on github

2024-12-03 11:47 UTC, merged