CI: build docker image
topology-foundation/ts-topology pull request #42
Opened 2024-07-10 16:02 UTC by joaopereira12

Resolves #25 

I've added a job to the Build Packages workflow that builds the docker images with docker compose.

2024-07-10 21:19 UTC, d-roak commented
It's not this. It's building the node docker image, and uploading it to the gh registry. It's not related w/ docker compose

2024-07-10 21:25 UTC, joaopereira12 commented
> It's not this. It's building the node docker image, and uploading it to the gh registry. It's not related w/ docker compose

Okay, my bad, i though the image could be buildt with compose, I will fix it tomorrow.

2024-07-11 16:19 UTC, joaopereira12 commented
I tested it on my forked project and the docker image was registered as you can see in the image bellow.

![image](https://github.com/topology-foundation/ts-topology/assets/77340776/1ab58b57-a4ce-476a-b0e2-280e7df1b5a8)

2024-07-11 16:28 UTC, d-roak requested changes

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build-docker-image.yml
> +    branches: [main]
release

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build-docker-image.yml
> +      id-token: write
do we need all of these?

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build.yml
> +
??

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build-docker-image.yml
> +
don't leave empty spaces at the end of files

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build-docker-image.yml
> +        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
aren't there versions for the actions (same applies for metadata-action and build-push-action)?

2024-07-11 16:28 UTC, d-roak commented on .github/workflows/build-docker-image.yml
> +        id: push
why do we need this id?

2024-07-12 15:08 UTC, joaopereira12 commented
I've fixed the file and added multi architectures build (arm & amd).

2024-07-15 10:51 UTC, d-roak approved these changes
lgtm

2024-07-15 10:51 UTC, merged