feat: LWW-Element-Set and OR-Set
topology-foundation/ts-topology pull request #56
Opened 2024-07-22 09:46 UTC by joaopereira12

LWW-Element-Set & OR-Set implemented in the builtins.

2024-07-25 19:22 UTC, joaopereira12 commented
I've finished the tests and the implementations. 
I also made the following changes in the existing CRDTs:
- I've fixed the compare method (instead of comparing with '==' it compares the values of each set)
- I've change the ID of the GCounter from string to number (I've read that the ID is a number from 0 to n-1) (https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type#G-Counter_(Grow-only_Counter))

2024-07-25 23:52 UTC, d-roak requested changes
Initial review

2024-07-25 23:52 UTC, d-roak commented on packages/crdt/src/builtins/GCounter/index.ts
> +}
Why?

2024-07-25 23:52 UTC, d-roak commented on packages/crdt/src/builtins/GCounter/index.ts
> -  counts: { [nodeId: string]: number };
We are mapping nodeId that come from libp2p. They are not numbers

2024-07-25 23:52 UTC, d-roak commented on packages/crdt/src/builtins/GCounter/index.ts
> +    for (let key in Object.keys(temp)) {
Why change?

2024-07-25 23:52 UTC, d-roak commented on packages/crdt/src/builtins/GCounter/index.ts
> +      this.globalCounter = Object.values(this.counts).reduce((a, b) => a + b, 0);
This shouldn't be inside the loop

2024-07-25 23:52 UTC, d-roak commented on packages/crdt/src/builtins/GSet/index.ts
> +    return (this._set.size == peerSet.set().size && [...this._set].every(value => peerSet.set().has(value)));
Doesn't Set type has a native every fn or something that does the same?

2024-07-26 03:53 UTC, d-roak requested changes
Comments on LWWSet

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +        }
properly write "Timestamp"

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +    add(element: T, timestamp: number): void {
force timestamp to javascript implementation, don't accept it as an argument (same for other fns)

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +    areSetsEqual(set1: Set<T>, set2: Set<T>): boolean {
put this fn outside the class as a helper fn (private) and rename it to `compareSets`

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +            }
why are u making the `!` assertion? also, why not just blindly add the elements?

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +    }
put outside the class

2024-07-26 03:53 UTC, d-roak commented on packages/crdt/src/builtins/LWWElementSet/index.ts
> +    }
and add bias as a parameter

2024-07-28 22:55 UTC, joaopereira12 commented
This branch also contains some changes in the GSet and contains the GSet and 2PSet tests. I've also added the GCounter and PNCounter to pass the pipeline tests, but I'll add them to their PR with the changes that I made.

2024-07-29 00:34 UTC, closed without merging