feat: LWW-Register impl & Tests
topology-foundation/ts-topology pull request #90
Opened 2024-07-31 17:02 UTC by joaopereira12

resolves #81

2024-08-03 16:45 UTC, d-roak requested changes

2024-08-03 16:45 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +type Timestamp = [timestamp: number, replicaId: string];
don't use `replicaId`, use `nodeId`

2024-08-03 16:45 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        if(compareTimestamps(this._timestamp, [timestamp, replicaId])) {
the assign is supposed to run locally, the timestamp will never be smaller

2024-08-03 16:45 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        return (this._timestamp <= register.getTimestamp());
this is wrong

2024-08-03 16:45 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +type Timestamp = [timestamp: number, replicaId: string];
don't create this type. Store both timestamp and nodeId in 2 vars within the class

2024-08-03 16:45 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        if(compareTimestamps(this._timestamp, register.getTimestamp())) {
extend the if logic here and delete the auxiliary function

2024-08-04 20:14 UTC, joaopereira12 commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        return (this._timestamp <= register.getTimestamp());
in this paper: https://dsf.berkeley.edu/cs286/papers/crdt-tr2011.pdf - they implement the compare function this way.
But i've seen some other solutions in the resources on the issue that don't have this function.

2024-08-05 04:22 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        return (this._timestamp <= register.getTimestamp());
timestamp is not a number, it's a tuple. that's why this is wrong

2024-08-05 04:28 UTC, d-roak requested changes

2024-08-05 04:28 UTC, d-roak commented on packages/crdt/tests/LWWRegister.test.ts
> +    // });
fix this

2024-08-05 04:28 UTC, d-roak commented on packages/crdt/src/builtins/LWWRegister/index.ts
> +        }
change to return prematurely if:
- the timestamp is bigger
- timestamp equal and nodeId lower

2024-08-05 09:09 UTC, d-roak approved these changes
lgtm

2024-08-05 09:09 UTC, merged