feat: Replicated Growable Array CRDT and Tests
topology-foundation/ts-topology pull request #93
Opened 2024-08-03 14:47 UTC by JanLewDev

Solves #83

2024-08-05 09:38 UTC, guiltygyoza commented on packages/crdt/src/builtins/RGA/index.ts
> +    indexWithTombstones(index: number): number {
this function maps virtual pointer (virtual id) to its actual index right? may be good practice to name it as such

2024-08-05 09:41 UTC, guiltygyoza commented on packages/crdt/src/builtins/RGA/index.ts
> +    read(index: number): T | null {
this function reads the value at an (actual) index. it seems that a function for reading the entire array out (no tombstoned values; sort by RGA's rules) is missing?

2024-08-05 09:42 UTC, guiltygyoza commented on packages/crdt/src/builtins/RGA/index.ts
> +    nextSeqNr(sequencer: Identifier): Identifier {
some functions here should be private methods. I'll defer to @d-roak for coding style guideline

2024-08-05 10:22 UTC, JanLewDev commented on packages/crdt/src/builtins/RGA/index.ts
> +    read(index: number): T | null {
I think getArray() does that now

2024-08-05 13:36 UTC, guiltygyoza commented on packages/crdt/src/builtins/RGA/index.ts
> +    read(index: number): T | null {
gotcha!

2024-08-23 06:28 UTC, d-roak requested changes

2024-08-23 06:28 UTC, d-roak commented on packages/crdt/src/builtins/RGA/index.ts
> +                ptr.nodeId === this._elements[offset].vid.nodeId
```suggestion
        for (let offset = 0; offset < this.elements.length; offset++) {
            if (
                ptr.counter === this.elements[offset].vid.counter &&
                ptr.nodeId === this.elements[offset].vid.nodeId
```

2024-08-23 06:28 UTC, d-roak commented on packages/crdt/src/builtins/RGA/index.ts
> +        this._elements[i].value = null;
```suggestion
        while (this.isTombstone(this.elements[i])) i++;
        this.elements[i].value = null;
```

2024-08-23 06:28 UTC, d-roak commented on packages/crdt/src/builtins/RGA/index.ts
> +        this._elements[i].value = value;
```suggestion
        while (this.isTombstone(this.elements[i])) i++;
        this.elements[i].value = value;
```

2024-08-23 06:28 UTC, d-roak commented on packages/crdt/src/builtins/RGA/index.ts
> +            nodeId: this._sequencer.nodeId,
```suggestion
        this.sequencer = {
            counter: Math.max(
                this.sequencer.counter,
                peerRGA.sequencer.counter
            ),
            nodeId: this.sequencer.nodeId,
```

2024-08-24 06:58 UTC, d-roak approved these changes
lgtm

2024-08-24 06:58 UTC, merged